name: Docker Image CI (PR)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
        matrix:
          cuda: [ "11.8.0", "11.7.1", "12.0.0" ]
          flavor: [ "runtime", "base", "devel"]
          os: [ "ubuntu22.04", "ubuntu20.04", "ubuntu18.04" ]
          python_version: [ "3.11.0", "3.10.9", "3.9.16", "3.8.16", "3.7.16"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Docker Login
      if: success()
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        tags: cuda-python:cu${{ matrix.cuda }}-py${{ matrix.python_version }}-${{ matrix.flavor }}-${{ matrix.os }}
        push: false
        build-args: |
          CUDA_VERSION=${{ matrix.cuda }} 
          FLAVOR=${{ matrix.flavor }} 
          SYS_VERSION=${{ matrix.os }} 
          PYTHON_VERSION=${{ matrix.python_version }}